### ISSUE TITLE
Set deliverable schedule and identify roles for subteams

### ISSUE THREAD

**Issue by bc** [bc/sp18#2]
#Subteams
1. EEG-Processing (Capstone 1)
- @marjanin 
2. VR-Modeling (Capstone 2)
3. Biomimetic-Design
-@mayumiishikawa
-@brandonmiura
4. Tendon-Drive
-@tstroobosscher
5. Scientific-Analytics
 -@bc
 -@medvidov2786

Advisors:
-@kian-ja Dr. Kian Jalaleddini, Ph. D.
-@cmlaine Dr. Chris Laine, Ph. D.
-Lena Weske

# Presently Unassigned:
-@fmdunlap
-@kujustin
-@ArfanR
-@sofiahurtado
-@ceubanks
-@nterrile

**Comment by nterrile** [comment]
We've divided the teams as follows:

EEG-Processing
- @sofiahurtado
- @fmdunlap
- @nterrile

VR-Modeling
- @ArfanR
- @kujustin
- @ceubanks
